version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  go-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: "mongodb://mongo:27017"

volumes:
  mongo_data:
